on: [push]

name: Maven

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        version: 1.8

    - name: Build with Maven
      run: mvn package --file pom.xml
